### ISSUE TITLE
Functionality Ideas

### ISSUE THREAD

**Issue by williamspiro** [williamspiro/HubSpot-Developer-Extension#1]
- [x] hsDebug=True query string button
- [x] jQueryFooter=True query string button
- [ ] stylesheet links
- [ ] Server debug report surfaced
- [ ] HubL snippets auto-complete (https://codepen.io/notoriousb1t/pen/dmYpVQ?editors=1010 ?)

**Comment by TheWebTech** [comment]
What is `Server debug report surfaced`?

**Comment by williamspiro** [comment]
I am going to close this out, as this was before we really got working on things. We can file individual issues for anything of incomplete items if people like those ideas.
