### ISSUE TITLE
in add module panel, the scrollbar is not styled like the others

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#102]
![](https://spin.d.pr/0vRwtr+)

**Comment by GonzaloTorreras** [comment]
I changed the selector to affect all the scrollbars (here)[https://github.com/williamspiro/HubSpot-Developer-Extension/commit/2e5de40d8de9e691fdd6f2561dc8afe6a8ca49b5]
