### ISSUE TITLE
Dark Theme - can't read dialogue when grouping fields.

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#110]
This may be fixed in the beta build I haven't noticed the issue Pete is seeing. Should check for it though unless @GonzaloTorreras knows he made this change. I just know I didn't.
![](https://spin.d.pr/wDtwOm+)

**Comment by GonzaloTorreras** [comment]
fixed [here](https://github.com/williamspiro/HubSpot-Developer-Extension/commit/904d4afbdec150ccdbc31794765dc4f3473f654d)
