### ISSUE TITLE
Add manifest icons to manifest.json

### ISSUE THREAD

**Issue by williamspiro** [williamspiro/HubSpot-Developer-Extension#124]
Let us add manifest icons to our [manifest.json](https://github.com/williamspiro/HubSpot-Developer-Extension/blob/master/manifest.json) file. This way we will have logos showing up throughout chrome for the extension, as opposed to their broken looking puzzle piece 😸 

https://developer.chrome.com/apps/manifest/icons

**Comment by TheWebTech** [comment]
really weird. I swear I had the icons thing in there before. completely agree we need to add that in.

I'm cool with this just being done as a patch and not waiting until v1.04

**Comment by TheWebTech** [comment]
This was addressed, forgot to close issue
