### ISSUE TITLE
Font size setting in developer settings menu is being overridden by our dark theme CSS

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#132]
**Describe the bug**
Code editor Font size setting in developer settings menu is being overridden by our dark theme CSS - which sets a font size. 

**To Reproduce**
1. go to developer settings panel, change code editor font size
2. font size will not change.

**Expected behavior**
It should change.

Only happens with Dark Theme enabled.

Gonzalo I assigned to both of us, figure if you're able to get to it before me that'd be good. I'm pretty busy up till September with projects and prepping for inbound - going to be giving a talk and running a booth.

**Comment by GonzaloTorreras** [comment]
[Fixed](https://github.com/williamspiro/HubSpot-Developer-Extension/commit/9a0e190ea7e909b2c23b59df3726b436016e96cc). 
New behaviour:
If you didn't changed the default value (12px) it will force the new value in the darktheme. But if you have changed it, the hardcoded size won't apply.

**Comment by TheWebTech** [comment]
Nice and clever fix!
