### ISSUE TITLE
Remove the backward compatibility for the OLD navigation Menu

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#134]
HubSpot has announced they are getting rid of the old navigation menu October 17th. 
Would be awesome if someone went through our design-manager.js file and removed the code and the detection of the old navigation menu. This is mostly just deleting code so should be easy, kinda fun even.

This should be submitted as a pull request, that way we can easily time the update with October 17th.

**Comment by Rnayak1** [comment]
is that issue is still open, if yes, I will like to do it

**Comment by TheWebTech** [comment]
Yep it's still open basically all of the code for this is in design-manager.js

Basically you can look for navVersion in the file, and anywhere it mentions version 3 - we need to remove the code for version 3.

https://github.com/williamspiro/HubSpot-Developer-Extension/blob/a9484875e65eb94c6a09ddca29055da3dda0ce64/design-manager.js#L88


https://github.com/williamspiro/HubSpot-Developer-Extension/blob/a9484875e65eb94c6a09ddca29055da3dda0ce64/design-manager.js#L137

https://github.com/williamspiro/HubSpot-Developer-Extension/blob/a9484875e65eb94c6a09ddca29055da3dda0ce64/design-manager.js#L154

https://github.com/williamspiro/HubSpot-Developer-Extension/blob/a9484875e65eb94c6a09ddca29055da3dda0ce64/design-manager.js#L197

There might be some more references in there, just thought I'd help point some out.

**Comment by TheWebTech** [comment]
Assigned to myself - just need to merge the PR once HubSpot makes their change. Thank you for doing this!
