### ISSUE TITLE
Translate Chrome Extension Description to French

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#153]
Hi we have a multi-lingual Chrome Extension and for French we don't have anyone who actually knows the language.

If someone could help us translate from English to French that would be awesome. Please do not just google translate it, that likely will result in a poor translation.

If you are doing it for hacktoberfest, you could put your translated text into a new text file or a markdown file so you can do a pull request.

Appreciate the help!

English text:
```
A Chrome/Chromium extension for HubSpot Developers that adds useful shortcuts to commonly used HubSpot query parameters, resources and tools for making HubSpot Development easier and more enjoyable.

*Buttons for activating commonly used HubSpot Query Parameters such as hsDebug, AMP, footer jQuery, and a cache buster
*Google Page Speed Insights Tester - great to see if moving jquery to the footer has a significant impact
*Quick access shortcuts to the most used areas of the HubSpot Dev Docs
*Optional Dark Theme for the Design Manager
*Optional Developer Menu injected into HubSpot Nav
*Mac users rejoice! we've solved the dark cursor on dark code editor problem!
*More features coming!

If you find a bug or want to request a feature please report it in our GitHub Issues. See our GitHub as well if you're interested in beta testing new versions.


Interested in helping translate the extension? We could use your help visit the GitHub! We need help translating to Spanish, German, French, and Japanese!

https://github.com/williamspiro/HubSpot-Developer-Extension
```

**Comment by AzogBiceps** [comment]
Hey, I translated it, but I can't find the fork where can I pull request it! Can you help me?

**Comment by TheWebTech** [comment]
You can put it in a new txt file and pull request to master

**Comment by TheWebTech** [comment]
@AzogBiceps if you're going for the hacktoberfest swag, you'll need to submit a pull request from your fork to this repository.

If you're new to github here's how:
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

If you're not doing it for hacktoberfest and are contributing simply because you're awesome, then you don't need to worry about it, I can copy the text you wrote, and note your username in our list of contributors.
