### ISSUE TITLE
Translate Extension to French - only requires editing one file, if you speak french you can do it!

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#154]
in the _locales folder there are folders for each language the extension supports, the messages.json file is a text file with all of the strings used throughout the extension.

We have users that are currently underserved because we don't have a French translation - none of the core developers working on the extension speak it, and we don't trust google translate enough to do a good job.

If you speak French, we could use your help. Here's what you'd need to do. create a new folder inside /_locales/ called "fr" then copy the [english messages.json file](https://github.com/williamspiro/HubSpot-Developer-Extension/blob/master/_locales/en/messages.json)

Translate all of the words in quotes next to the word "message:"
The description - is purely there to make it easy to identify what the message is talking about/means you don't need to translate that.

https://github.com/williamspiro/HubSpot-Developer-Extension/blob/master/_locales/en/messages.json

If you're coming here for Hacktoberfest, thank you for supporting the open source community we love you, and good luck on the Hacktoberfest swag!

**Comment by MisterJack49** [comment]
Hi can I take it ?

**Comment by TheWebTech** [comment]
@MisterJack49 Yes definitely, thank you!

**Comment by MisterJack49** [comment]
Can you tell me more on the "Bust Cache" action ? Does it clear the cache or something else ?

**Comment by TheWebTech** [comment]
@TheWebTech short answer: Sort of.

HubSpot CMS has server side CDN caching, and when you hit the "bust cache" button it loads your current page with that caching disabled, by adding a query parameter to your URL.

It has no effect on your web browser's cache.

hope that helps

**Comment by MisterJack49** [comment]
Yes thank you
