### ISSUE TITLE
April Fools Clippy

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#170]
I think it'd be great to add as an April Fools joke a little pop-up clippy like thing in the design manager.
![sprocky](https://user-images.githubusercontent.com/5492388/48432327-af008880-e739-11e8-9a79-3786afa663cc.png)
image courtesy of AJ Laporte

however we implement this we'd need to make it easily dismissable and clear that it's a joke and from the chrome extension not HubSpot themselves. Would also be good to be able to prevent it from showing up ever again. we don't really want to annoy people.

**Comment by TheWebTech** [comment]
Sprocky AI file
https://spin.d.pr/UXzMoc

I'm thinking he should be dismiss-able, and more permanently killable(maybe later we'll add a way to re-activate him).

Now guys - what are some things he should say?

**Comment by TheWebTech** [comment]
@williamspiro can you add 
https://github.com/bradhave94
to make it easier to collaborate on this feature. Sprocky is coming!!!! :)

**Comment by williamspiro** [comment]
🚀 all set

**Comment by TheWebTech** [comment]
Thank you @williamspiro, @bradhave94 I can't seem to tag you for some reason but now you can commit to that feature branch directly.

**Comment by TheWebTech** [comment]
Haven't integrated it into the extension yet but plan to. I made Sprocky an animated SVG, with a few animations.
https://codepen.io/thewebtech/pen/BbqORo?editors=1100

**Comment by TheWebTech** [comment]
PR #212
Is bringing sprocky to the masses. Will be publishing the update in the stable channel soon
