### ISSUE TITLE
Publishing updates is blocked by an EU regulation that's fairly unclear

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#253]
I went in to see if I could update the chrome extension with @jazzyclimber 's #251 changes but I'm prompted with the following modal which blocks all updates till you answer it:

![Access to the developer dashboard is blocked by a modal forcing selection of trader or non trader selection by developers](https://user-images.githubusercontent.com/5492388/213875240-b51bc964-52cd-4932-a2cf-a5bd17b5c907.png)

Reading through it and reading through the help article https://developer.chrome.com/docs/webstore/trader-disclosure/ basically was meaningless to me.

I'm not sure whether we should be designating the account as a trader or not. It seems the regulation on this may have been poorly written. We're not the only ones with this confusion:

https://stackoverflow.com/questions/72488292/chrome-webstore-developer-dashboard-am-i-a-trader-or-non-trader

For clarity sake, there are no paid features in the chrome extension, it is not owned by HubSpot. @GonzaloTorreras is the owner. He has the right to later add paid functionality should he choose, as well as the ability to promote his business through it.

Based on the stackoverflow article it sounds like should Gonzalo later want to add a paid feature he could change this self declaration from non-trader to trader.

So I'm leaning towards picking non-trader, but I have to say the wording is as clear as mud. Anyone have any thoughts?

**Comment by jazzyclimber** [comment]
@TheWebTech The way that this reads to me is that a Trader has to do with contracts and letting a user know if they are protected under consumer rights. Really Gonzalo isn't a business entity, nor is the extension a real business service or anything. I think it would be most representative to go with the **"Non-Trader" status**. 

While gonzalo is a developer and his "trade" might be considered to be programming or software engineering, he is not HubSpot, like you mentioned, nor is this a HubSpot extension. 

I would suspect that if we were a cyber security firm and made an extension for our product then we would fall under the "Trader"category. 

I don't think that is the case now.

**Comment by TheWebTech** [comment]
Marking as non-trader. Can change later if required. Will try getting that update out.
