### ISSUE TITLE
It appears that the default for the dark skin is that it's enabled - should be opt in

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#35]
The dark theme seems to be kicking in right away. We just need to change the default setting.

**Comment by TheWebTech** [comment]
actually I'm not sure on this, I might have enabled the feature myself and forgotten about it.

Will keep this open and pay attention to anyone commenting about it kicking in automatically or something on slack.

**Comment by GonzaloTorreras** [comment]
Confirmed,
I updated to the new version and have been auto activated

**Comment by TheWebTech** [comment]
Issue is resolved in latest build and published to store.
https://github.com/williamspiro/HubSpot-Developer-Extension/releases/tag/v1.01.1
