### ISSUE TITLE
rich text field popups

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#83]
Some of the popups from the rich text field need some love.
![link popup](https://spin.d.pr/PlRLkf+)

The "embed" button's modal the tabs require hovering to read the text.

These are minor-ish issues.

**Comment by GonzaloTorreras** [comment]
Fixed [here](https://github.com/williamspiro/HubSpot-Developer-Extension/commit/b1cc637ded1d63edf8a894b3e81b3f1ed71c9683)
