### ISSUE TITLE
v1.03-beta scrollbar z-index is still higher than success modal

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#87]
scrollbar shows across the top of the success modal due to z-index issue.

Current value is 500, probably fine around 200(not sure what the success modals is)

**Comment by GonzaloTorreras** [comment]
Hmm, I feel like it's not on top of the success notification, but the success notification has an opacity background.
If that disturb you we can make it solid 👍

**Comment by TheWebTech** [comment]
hmm, maybe HS fixed it, not sure. the opacity is fine.
I'll keep an eye out for it

**Comment by TheWebTech** [comment]
Think HubSpot fixed this
