### ISSUE TITLE
Change button Icon from being a Panda, to something that better reflects what the extension does

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#9]
Change the icon to something that better reflects what the extension is for.

If anyone has ideas for a graphic throw em out there.

One idea, maybe a version of the HubSpot sprocket, that's some how geekier looking?

![HS Sprocket](https://spin.d.pr/j8Et0d+)

Like maybe a version where it's got `<` `>` on the sides of it?

@williamspiro since you work for HS, do you think they'd take issue with us using that graphic for this project? 

I mean it's kind of an official unofficial plugin in a way because you are an employee there, but there are people (Gonzalo and I) who are not employees contributing

**Comment by williamspiro** [comment]
I can touch base with the powers that be about logo usage. 

I created an issue for readiness for Chrome store here https://github.com/williamspiro/HubSpot-Developer-Extension/issues/10

**Comment by TheWebTech** [comment]
just re-pinging since this is a side project for all of us and if your monday is like mine it quickly gets swamped..

@williamspiro and @GonzaloTorreras how do you feel about the new icon
https://spin.d.pr/kgt1aX+

Good enough for V1 chrome store?
![icon](https://user-images.githubusercontent.com/5492388/41537243-7f5d3596-72cd-11e8-8b17-d16f52dc3f36.png)

**Comment by GonzaloTorreras** [comment]
good for me!

**Comment by TheWebTech** [comment]
Sounds good I'll merge this and @williamspiro, if the powers that be at HS take issue with it's similarity to the HS logo you can let them know we will respect a request from them to change it, and would request any guidelines they have for referring to HubSpot, as we obviously need to be able to mention HubSpot in the extension description - currently have the extension named with HS in the name etc.
