### ISSUE TITLE
dark theme - while dragging an item in the finder over a folder the folder's name becomes impossible to read

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubSpot-Developer-Extension#99]
dark theme - while dragging an item in the finder over a folder the folder's name becomes impossible to read.

We just need to make sure the background color doesn't change to be too bright.

hard part is finding out what class they're using to add that style. since you have to drag to see it...

**Comment by GonzaloTorreras** [comment]
Fixed in [last commit](https://github.com/williamspiro/HubSpot-Developer-Extension/commit/5406f4776c6ca8e02a725599045ec17da909bbb4)
